sudo: false
dist: focal

language: python
python:
- "3.10.9"

before_install:
- python --version
- pip install --upgrade pip
- pip install setuptools_rust

script:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker pull flybase/proformatestdb
- python -m pytest -v
- pip install .
env:
  global:
  - secure: AiUFDikpesvr67hIGFJ1llby5T8hPJrfoLAscpP5hGQD/k9CB3vTE44B48obbQ9NmA3SRDEKtDYRtz4+nJ5dcUDmAjEd3azHgXZ8fRJ7hwJB68iDiq067mdt4ote2no1CrDZLLojFJy5GUFJlxpib9A3NOSa10ljJ5CfCGMka7c+k4ffLcExTZy3w5QWmo052CMksDWBAXweu1+SI6v/MpSiCb/gZ2BCT5zwkkgSp1gE61AXMa6gwZlbRQSL9Q/gHnpINM2u8ZQAAailp8HgFIV2GKfdMMxiq6H3K24pfBMg6mAQGAGsCnYj+dDYyXPxqqWkr/XMTn9IKEHauxU2Uykry2U5FiF1AjuubU6LfBfequXo0YtMfj5iaQ1weigB695vdRTPUTI7QOcjlHj7D1SdjwbnwOB839CSevXEVqYLuldnoQt+/3KUNmchFfaPauxasD8OQ9A2hh7aSAUFzXzVOsDYJcusbNzTETVSgzf2uS+WYFjoFdRbKw9vHbrIHCojEb7wu/ZcIpsPg36ad8mbFJB1PSqkagvjhpzSHqK14El64ZQcvBO5wudf6/EGLQC0Bu98KjLaVBWseblMte/6+nvYRL3a43kW6YO0bS7ppkhuCz3QkLIqvPcJEUrn7mCT2gAHqw6gnG8fPjBSec33mdNHpwP7Z0NOSZAfS3E=
  - secure: OkJlIiETA7gxvDYQfVBVpMZZbVCMk+XkzQjFsN77BZhe1lf6mVQk4gzPBKlzP5OiN2y1fInwg5jO0menCVksrKiEeWyp4KMngNygSmiR4tKPaLIE+HhTo4N/6JZJwpURjmzJN0VTmtZIhDr1YkUv599rLLf+9ivfKMGuHWDBzE9MI6Qyb2u6gKf4A6ChKKBb4qdXwIlZmjY7WHitVvTGT3X649Ij3AOccoovdTQwv7kdOPLKdOoiivgEb+jOheR3rG6l7WqiltNT2uLEwKfKaWRDlGjrVZvqd0wRTVWbdcMiRVELpiGVBmnExUpwTT3OvM6YxWoM+E31m99t4IOAcsbXdFCkR/ohKkkzyJAdJbPmVtezuV75tgV3EsGov3LkVoBxK8g7BAIu82XDdd6LnhdEBkKS8ddj71a62JDydkamqiWSVIsaA8A2i7QDxnJlKnH10aTikAaVjwpm2WugnSFnhaMClNCSxiyp4Uy7QKyIeNDs2cFD7OhRmWKTjl4ZmL+yCpX4iQupIiBhHGbBMSLGwn/MAD3pmxzKJuTj+gPDQRsgOzAwxB2OVhGDbJUmOswt5iRmDMlTybiwNpBWss1RTIBvOJw+2Ox8VZTAlzqb6h9ad/ANRBpvJPnsvCJb4WcJd4E2gkLWvbF76MrFSGdPD1Aqzsi77OyQMTnQz1g=
